### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by ernestez** [nachowski/warpwallet_cracker#1]
I keep getting the below response when i try to run the program: Please check and let me know what i am not doing right.

root@vps:~/warp1# ./run.sh
./warpwallet_cracker.go: line 1: package: command not found
./warpwallet_cracker.go: line 3: syntax error near unexpected token `newline'
./warpwallet_cracker.go: line 3: `import ('

**Comment by nachowski** [comment]
Did you build warpwallet_cracker using `go build` first?

What happens when you run
`./warpwallet_cracker 1MkupVKiCik9iyfnLrJoZLx9RH4rkF3hnA a@b.c`

**Comment by ernestez** [comment]
When i build this is the response i get: go build warpwallet_cracker.go
warpwallet_cracker.go:4:3: cannot find package "github.com/ctz/go-fastpbkdf2" in any of:
warpwallet_cracker.go:4:3:: command not found
root@vps:~/warp1#         /usr/lib/go/src/pkg/github.com/ctz/go-fastpbkdf2 (from $GOROOT)
bash: syntax error near unexpected token `from'
root@vps:~/warp1#         /root/.go/src/github.com/ctz/go-fastpbkdf2 (from $GOPATH)
bash: syntax error near unexpected token `from'

and below is the response i get when i run:
./warpwallet_cracker 1MkupVKiCik9iyfnLrJoZLx9RH4rkF3hnA a@b.c
bash: ./warpwallet_cracker: No such file or directory

**Comment by ernestez** [comment]
I have resolved the issue. I run: go get github.com/ctz/go-fastpbkdf2 and it was fixed. Its working now.

Thanks
