### ISSUE TITLE
how to install on windows

### ISSUE THREAD

**Issue by 199862** [nachowski/warpwallet_cracker#6]
Hi

Could it be possible for you to make a short list for installing?
I mean, I installed GO, but when I try to Go GET, GCC is missing
If I try GO BUILD it's the same
Then I tried cigwin, tdm-gcc, mingw64 and I get diferent messages of err

After installing Go, what would you recommend, mingw64 or cygwin?

**Comment by 199862** [comment]
Hi, Finally I did it. it cost me a lot of days (all day each) installing, uninstalling, searching, learning, etc but its a terrific program. Best Regards

**Comment by rama942** [comment]
What OS you use.,?

**Comment by rama942** [comment]
I try many time still failed :'( need tutorial video,. Yesterday error GCC, and problem solved, and after that error openssl/sha.h and i stuck to fix it., please help me., :3

**Comment by rama942** [comment]
I use OS windows 7 x64 ultimate

**Comment by 199862** [comment]
Hi, I use windows 10 pro.
As I see, you have the same problems I had
I don't know if what I did is the optimal but it works. surely is better modifiyng PATH's but I couldn't  find it.
To solve openssl/sha.h I copied openssl directory under fastpbkdf2

**Comment by 199862** [comment]
sorry go-fastpbkdf2

**Comment by nachowski** [comment]
Glad you solved thus by yourself! If you could make a list of steps to build this under Windows feel free to open a PR.

**Comment by rama942** [comment]
error openssl done :D and than i have new problem :'( 

http://prntscr.com/h62qrp

**Comment by 199862** [comment]
I didn't take note, but I will try to remember/recreate and maybe try to install in another pc.
the file corresponding to library  lcrypto is libcrypto.a , is part of openssl,  search for it in you pc and you need to paste it in another directory
where? I see yuo use TDM-gcc and I used mingw64 so you will have to find the place
in my case was 
C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev0\mingw64\opt\lib

**Comment by 199862** [comment]
sorry in my case I pasted it here
C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev0\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0

**Comment by rama942** [comment]
I think I need to uninstall all programs and start from scratch :D Fighting :D 

can you post link all program do you use.,

**Comment by rama942** [comment]
I try to make folder location same with your PC 
http://prntscr.com/h6c20j


http://prntscr.com/h6c3k0

**Comment by rama942** [comment]
http://prntscr.com/h6c3k0

**Comment by 199862** [comment]
ok delete or rename collect2.exe

**Comment by 199862** [comment]
I think is the last step

**Comment by rama942** [comment]
http://prntscr.com/h6c82v
why don't build warpwallet_cracker.exe
can you explain to me :3

**Comment by 199862** [comment]
Where did you get libcrypto.a ? could you try downloading from this
https://github.com/owncloud/ios

**Comment by rama942** [comment]
from openssl
http://prntscr.com/h6cdp1

**Comment by rama942** [comment]
why so different size :D ahahaha
http://prntscr.com/h6ceq9

**Comment by rama942** [comment]
oh god whyyyy

and now file not recognized
http://prntscr.com/h6chku
:'3

**Comment by 199862** [comment]
wow..... lets go back to the one in your pc.... but now I am thinking because is all i did.

**Comment by rama942** [comment]
can you include all the link programs you use in your pc please ...?

**Comment by 199862** [comment]
![image](https://user-images.githubusercontent.com/30844838/32410812-4db7db1c-c18f-11e7-8ce8-7a1e3081f11f.png)
well, show me the path, go root

**Comment by rama942** [comment]
do you have teamviewer sir...? i think better you remote my pc :D

**Comment by 199862** [comment]
it´s only go and ming
![image](https://user-images.githubusercontent.com/30844838/32410847-0a845aae-c190-11e7-88d3-840d0947f206.png)

**Comment by 199862** [comment]
I dont have team viewer, i was going to install but never did

**Comment by 199862** [comment]
and git

**Comment by 199862** [comment]
I modified the readme.md of warpwallet but is on revision, can you see it?

**Comment by rama942** [comment]
this is mine 

http://prntscr.com/h6cpu7

blank at the comment

http://prntscr.com/h6crxk

**Comment by rama942** [comment]
i don't see it sir :3

**Comment by rama942** [comment]
sir i have question first 
where you get the openssl folder...?
from this 
https://github.com/owncloud/ios

or another link...?

**Comment by 199862** [comment]
As I told you at the begining, I didn't take notes, now I realize it's a mac page , I have another posibility I was trying but finally I think I got from my pc. This is the other one I tried
https://github.com/krzyzanowskim/OpenSSL/tree/master/lib-ios

**Comment by 199862** [comment]
from the first image, something is wrong with  path because it must find it, can you tell me your path towarp wallet. mine is 
C:\Users\MYUSER\go\src\github.com\ctz\go-fastpbkdf2\openssl
C:\Users\MYUSER\go\src\github.com\nachowski\warpwallet_cracker

**Comment by rama942** [comment]
http://prntscr.com/h6cxtl
http://prntscr.com/h6cy3e
so different
in C:\users\...\go\src\github.com\ i don't have folder like ctz

i create new projects may i wrong with this GOPATH
http://prntscr.com/h6cyct

**Comment by 199862** [comment]
I think gopath is ok as wll as goroot

**Comment by rama942** [comment]
do you can upload libcrypto.a from your computer sir...?

**Comment by 199862** [comment]
ok

**Comment by rama942** [comment]
ok, I am waiting sir 👍

**Comment by 199862** [comment]
![image](https://user-images.githubusercontent.com/30844838/32411036-49b418e4-c196-11e7-8038-bcf45081b659.png)

**Comment by 199862** [comment]
ok hope not have problem help2ppl

**Comment by 199862** [comment]
at google mail

**Comment by rama942** [comment]
rmrboy942@gmail.com

**Comment by 199862** [comment]
![image](https://user-images.githubusercontent.com/30844838/32411070-0d8f1886-c197-11e7-871c-2ae732b8c96e.png)

**Comment by rama942** [comment]
![1orh7xh-rhcgpiezl7ffyq](https://user-images.githubusercontent.com/8907605/32411086-da7b9d70-c204-11e7-82ef-aecd0ee096a6.png)

**Comment by rama942** [comment]
did i miss something...?
i don't have perl64., what is that...?

**Comment by rama942** [comment]
why you have two mingw64...?

**Comment by 199862** [comment]
well don't have to be exactly the same I have previous instalations of perl and ruby I don' think is important.
about ming I supossed the installer did it.

**Comment by rama942** [comment]
can you post two PATH mingw64...?
first 
C:\Program Files\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev0\mingw64\bin;
and 
second Path is
...?

**Comment by 199862** [comment]
ok about ming I expanded the window and I think i did because is not logical, it left in all the modificatoins I did
![image](https://user-images.githubusercontent.com/30844838/32411160-abf044da-c199-11e7-8628-886c46eb0cad.png)

**Comment by 199862** [comment]
ok did you try libcrypto?

**Comment by rama942** [comment]
Finally i did it Thankyou sir :D 

![screenshot_1](https://user-images.githubusercontent.com/8907605/32411200-078d5e68-c208-11e7-8db0-6a5d5026caca.png)

**Comment by rama942** [comment]
I try Libcrypto from your pc :D and i did it :D

**Comment by 199862** [comment]
ok I will look where did i get it
Congratulations

**Comment by rama942** [comment]
do you know, how to continue bruteforce not from the beginning...?

$ ./run.sh 
Using address "1MkupVKiCik9iyfnLrJoZLx9RH4rkF3hnA" and salt "a@b.c"
Tried 4 passphrases in 2.269448485s [last passphrase: 2zZM3L1C]

**Comment by rama942** [comment]
i don't get it.,

**Comment by 199862** [comment]
My unique trying is the installation of windows but now I hope you can belp me. Where do you run ./run.sh I would like to try it

**Comment by rama942** [comment]
I want to try too, that's why i ask you, 😆 because i don't know run ./run.sh and start not from begining., because when i open 2 or 3 run.batch they reapet passphrase from another cmd but still random.,

**Comment by 199862** [comment]
Ok we need more investigation

**Comment by rama942** [comment]
Aye sir >.< 
Roger that.,

**Comment by rama942** [comment]
how to go build warpwallet_cracker_test.go
because i have error message.,

http://prntscr.com/h6svsx

**Comment by nachowski** [comment]
You don't need to explicitly build the test file. You can run tests using go test, however this is completely optional.

**Comment by rama942** [comment]
i have message error like this
http://prntscr.com/h6w403
