### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by beuzathor** [nachowski/warpwallet_cracker#7]
When i luanch go build warpwallet_cracker.go i have this :+1: 
warpwallet_cracker.go:4:3: cannot find package "github.com/ctz/go-fastpbkdf2" in any of:
	/usr/src/pkg/github.com/ctz/go-fastpbkdf2 (from $GOROOT)
	($GOPATH not set)
warpwallet_cracker.go:12:2: cannot find package "github.com/vsergeev/btckeygenie/btckey" in any of:
	/usr/src/pkg/github.com/vsergeev/btckeygenie/btckey (from $GOROOT)
	($GOPATH not set)
warpwallet_cracker.go:5:2: cannot find package "golang.org/x/crypto/scrypt" in any of:
	/usr/src/pkg/golang.org/x/crypto/scrypt (from $GOROOT)
	($GOPATH not set)

**Comment by nachowski** [comment]
Per README, you need to run
`go get ./..`

Also see https://stackoverflow.com/a/44728209
